name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/**'
      - 'src/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v4
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-v2-${{ hashFiles('*.nimble') }}

    - name: Setup nim
      uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: 2.2.0

    - name: Install Packages
      run: nimble install -d -y

    - name: Build Webfisher
      run: nimble build -Y

    - name: Upload Linux artifact
      if: ${{ runner.os }} == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: webisher-linux
        path: webfisher

    - name: Upload Windows artifact
      if: ${{ runner.os }} == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: webfisher-windows
        path: webfisher.exe

